version: "3.7"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - db
    networks:
      - application-network-local
    tty: true
    command: tail -f /dev/null
  db:
    image: postgres:12.0
    ports:
      - 1432:5432
    volumes:
      - application-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - application-network-local
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
        # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - application-network-local
    command: tail -f /dev/null
    # this is needed for having react server available
    stdin_open: true
volumes:
  application-db:
networks:
  application-network-local:
    name: application_network_local
